### ISSUE TITLE
error: Query failed with (18): header failed basic validation

### ISSUE THREAD

**Issue by berelton** [confio/ts-relayer#221]
Hello, getting the following error:

```
root@wasm:~# ibc-setup ics20 -v
verbose: Queried unbonding period {"seconds":1814400}
verbose: Create Tendermint client
verbose: Queried unbonding period {"seconds":1209600}
verbose: Create Tendermint client
info: Connection open init: 07-tendermint-11 => 07-tendermint-1774
verbose: Get latest commit
verbose: Get validator set for height 194110
verbose: Get header for height 194110
verbose: Get validator set for height 194104
verbose: Get header for height 194104
verbose: Update Tendermint client 07-tendermint-1774
info: Connection open try: 07-tendermint-1774 => 07-tendermint-11 (connection-9)
verbose: Get latest commit
verbose: Get validator set for height 3018512
verbose: Get header for height 3018512
verbose: Get validator set for height 3018502
verbose: Get header for height 3018502
verbose: Update Tendermint client 07-tendermint-11
error: Query failed with (18): header failed basic validation: commit signs block 8AA621F24A6B226C9ECFC153881B5E49124ACF167697AFA27225732A0A1DFC5B, header is block 2F3EC32F5CFA04A5C094A7561A73759B28B17B387D353437604A6F3AF7291002: invalid request
```

What can be the issue?

**Comment by ethanfrey** [comment]
I cannot help without more info.

Can you please tell me which two chains you are connecting. And if you can reproduce this everytime you send.

I need `~/.ibc-setup/registry.yaml` and `~/.ibc-setup/app.yaml` (the later please remove the mnemonic). That could give me a test case at least.

Some chains have forked the cosmos-sdk which may cause issues. This has been tested against cosmos sdk 0.42 in simapp and wasmd and cosmos sdk 0.44 in naiad

**Comment by berelton** [comment]
@ethanfrey thanks for the response.

`app.yaml`:
```
src: deweb
dest: osmosis
mnemonic: <few words>
```

`registry.yaml`:
```
version: 1

chains:
  deweb:
    chain_id: deweb-testnet-0
    prefix: deweb
    gas_price: 0.1udws
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    rpc:
      - https://rpc-deweb.deweb.services:443
  osmosis:
    chain_id: osmosis-1
    prefix: osmo
    gas_price: 0uosmo
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    rpc:
      - https://rpc-osmosis.blockapsis.com:443
```
