### ISSUE TITLE
error: Query failed with (6)

### ISSUE THREAD

**Issue by taitruong** [confio/ts-relayer#261]
Hi, trying to setup relayer for testnets between osmosis and juno.

I get this error:
```sh
error: Query failed with (6): rpc error: code = Unknown desc = header failed basic validation: commit signs block A74BBBBFE5BE665859CE4179D7A317DF9B31294001BFC6C49FEF7CF3464497DD, header is block 41BC871ED066CF8D423F0DDE0C33ABF9705CF1BA19B90A7DF7DFB66123068210 [cosmos/ibc-go/v3@v3.3.0/modules/light-clients/07-tendermint/types/header.go:62] With gas wanted: '0' and gas used: '13368' : unknown request
```

I added these to registry.yaml:

```yaml
chains:
  osmosis-testnet:
    chain_id: osmo-test-4
    prefix: osmo
    gas_price: 1uosmo
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    estimated_block_time: 7000
    estimated_indexer_time: 250
    rpc:
      - https://osmosistest-rpc.quickapi.com:443
  juno-testnet:
    chain_id: uni-5
    prefix: juno
    gas_price: 0.025ujunox
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    estimated_block_time: 7000
    estimated_indexer_time: 250
    # request in juno faucet channel https://discord.gg/TfsuB6yd
    # faucet: https://faucet.uni.juno.deuslabs.fi
    rpc:
      - https://rpc.uni.junonetwork.io:443
```

app.yaml:

```yaml
src: osmosis-testnet
dest: juno-testnet
mnemonic: <...>
´´´
